package cmd

import (
	"fmt"
	"os"
	"text/template"

	"github.com/spf13/cobra"
)

const cronTemplate = `#
# Minecraft Server Manager Cron
#
# Backs up worlds, rolls logs, starts crashed servers, and deletes old archives
#
# Generated by: msm cron generate
# For more information visit: https://github.com/msmhq/msm
#

# Backs up all worlds for all servers at {{ .MaintenanceHour }}:02
02    {{ printf "%02d" .MaintenanceHour }}  *   *   *   {{ .Username }}   {{ .MSMBinary }} worlds backup --all

# Rolls the logs for all servers at {{ .LogrollHour }}:55
55    {{ printf "%02d" .LogrollHour }}  *   *   *   {{ .Username }}   {{ .MSMBinary }} logroll --all

# Start any crashed servers each hour
@hourly               {{ .Username }}   {{ .MSMBinary }} start

# Deletes all server log files older than {{ .RetentionDays }} days
10    {{ printf "%02d" .MaintenanceHour }}  *   *   *   {{ .Username }}   find {{ .ServerStoragePath }}/*/logs -maxdepth 1 -mtime +{{ .RetentionDays }} -type f -name "*.log.gz" | xargs rm --force

# Deletes all server backup files older than {{ .RetentionDays }} days
12    {{ printf "%02d" .MaintenanceHour }}  *   *   *   {{ .Username }}   find {{ .BackupArchivePath }} -maxdepth 2 -mtime +{{ .RetentionDays }} -type f -name "*.zip" | xargs rm --force

# Deletes all msm log files older than {{ .RetentionDays }} days
14    {{ printf "%02d" .MaintenanceHour }}  *   *   *   {{ .Username }}   find {{ .LogArchivePath }} -maxdepth 2 -mtime +{{ .RetentionDays }} -type f -name "*.log.gz" | xargs rm --force

# Deletes all server world backup files older than {{ .RetentionDays }} days
16    {{ printf "%02d" .MaintenanceHour }}  *   *   *   {{ .Username }}   find {{ .WorldArchivePath }} -maxdepth 3 -mtime +{{ .RetentionDays }} -type f -name "*.zip" | xargs rm --force
`

type cronData struct {
	Username          string
	MSMBinary         string
	MaintenanceHour   int
	LogrollHour       int
	RetentionDays     int
	ServerStoragePath string
	BackupArchivePath string
	LogArchivePath    string
	WorldArchivePath  string
}

var cronCmd = &cobra.Command{
	Use:   "cron",
	Short: "Cron file management",
}

var cronGenerateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate cron file from configuration",
	Long: `Generate a cron file based on your MSM configuration.

The generated cron file uses settings from msm.conf:
  CRON_MSM_BINARY            - Path to msm binary (default: /usr/local/bin/msm)
  CRON_MAINTENANCE_HOUR      - Hour for backups and cleanup (default: 5)
  CRON_ARCHIVE_RETENTION_DAYS - Days to keep archives (default: 30)

Output is written to stdout. Redirect to a file or pipe to 'msm cron install'.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return generateCron(os.Stdout)
	},
}

var cronInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install cron file to /etc/cron.d/msm",
	Long: `Generate and install the cron file to /etc/cron.d/msm.

Requires root privileges. The file will be created with mode 0644.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cronPath := "/etc/cron.d/msm"

		f, err := os.OpenFile(cronPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
		if err != nil {
			return fmt.Errorf("failed to open %s (are you root?): %w", cronPath, err)
		}
		defer f.Close()

		if err := generateCron(f); err != nil {
			return err
		}

		fmt.Printf("Installed cron file to %s\n", cronPath)
		return nil
	},
}

func generateCron(w *os.File) error {
	logrollHour := cfg.CronMaintenanceHour - 1
	if logrollHour < 0 {
		logrollHour = 23
	}

	data := cronData{
		Username:          cfg.Username,
		MSMBinary:         cfg.CronMSMBinary,
		MaintenanceHour:   cfg.CronMaintenanceHour,
		LogrollHour:       logrollHour,
		RetentionDays:     cfg.CronArchiveRetentionDays,
		ServerStoragePath: cfg.ServerStoragePath,
		BackupArchivePath: cfg.BackupArchivePath,
		LogArchivePath:    cfg.LogArchivePath,
		WorldArchivePath:  cfg.WorldArchivePath,
	}

	tmpl, err := template.New("cron").Parse(cronTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	return tmpl.Execute(w, data)
}

func init() {
	cronCmd.AddCommand(cronGenerateCmd)
	cronCmd.AddCommand(cronInstallCmd)

	rootCmd.AddCommand(cronCmd)
}
